<?php
/******************************************
US English
Admin Technology Language
******************************************/

$lang['domains']					= 'Domains';
$lang['error_must_select']			= 'You must select a domain to organize';
$lang['error_not_found']			= 'The requested domain could not be found.';
$lang['organize_domain']			= 'Organize "%s" Technology';
$lang['organize']					= 'Organize';
$lang['domain_id']				= 'ID';
$lang['domain_form']				= 'Domain Form';
$lang['name']						= 'Name';
$lang['slug']						= 'Slug';
$lang['description']				= 'Description';
$lang['excerpt']					= 'Excerpt';
$lang['sequence']					= 'Sequence';
$lang['image']						= 'Image';
$lang['seo_title']					= 'SEO Title';
$lang['meta']						= 'Meta Data';
$lang['message_domain_saved']		= 'The domain has been saved!';
$lang['error_file_upload']			= '<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_domain']	= 'The domain has been deleted.';
$lang['current_file']				= 'Current File';
$lang['confirm_delete_domain']	= 'Are you sure you want to delete this domain?';
$lang['add_new_domain']			= 'Add New Domain';
$lang['no_domains']				= 'There are currently no domains';
$lang['attributes']					= 'Attributes';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= 'Drag and drop the products in the order you would like them to appear.';
$lang['sku']						= 'SKU';
$lang['price']						= 'Price';
$lang['sale']						= 'Sale';
$lang['max_file_size']				= 'Max File Size';